### PR TITLE
Adds scripts for setting up Nextcloud dev env on openSUSE.

### PR DESCRIPTION
**Pull request by camilasan**
WIP:
- update list of packages to install.
- Includes README with instructions.

@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Awesome! :) Is there even just a way to find out if it's OpenSuse? Then we could keep the script the same and only change the commands which need changing. (Which are the package names and the web server user & directory, right?)

**Comment by jancborchardt** [comment]
Merging as the mentioned improvements can also be done later. :)

**Comment by camilasan** [comment]
sorry, I couldn't reply before. But yes we could probably pass openSUSE as parameter or something... instead of a separated script.

**Comment by jancborchardt** [comment]
Or maybe running `lsb_release -a` which for me puts out:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
We could just check if the "Description" or "Distributor" has "opensuse" in it (or however it shows up for you), and if it does, do the OpenSUSE-specific commands?

**Comment by jancborchardt** [comment]
Seems like maybe `cat /etc/os-release` is better, since lsb_release might not be installed: https://www.cyberciti.biz/faq/find-opensuse-suse-enterprisel-inux-version-command/

**Pull request merged**
