### PR TITLE
update for macOS 10.13

### PR DESCRIPTION
**Pull request by xMartin**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Wasn't watching the repository so far and only saw it now. Good fix! :)

**Comment by jancborchardt** [comment]
Ah, actually changed it recently so the tutorial is shorter and has a similar notice already:

https://github.com/jancborchardt/nextcloud-scripts/blob/master/Nextcloud%20macOS%20development%20environment.md

**Comment by xMartin** [comment]
Maybe you want to combine both, because what is "new version"?

**Comment by jancborchardt** [comment]
@xMartin good call – do you want to edit the current readme?

**Comment by jancborchardt** [comment]
@xMartin see pull request at https://github.com/jancborchardt/nextcloud-scripts/pull/3 :)

**Comment by xMartin** [comment]
👍

**Pull request closed without merging**
